### ISSUE TITLE
Multiple twitter sliders

### ISSUE THREAD

**Issue by rayss** [alexbtk/amos-ss16-proj9#11]
![multiple twitter sliders](https://cloud.githubusercontent.com/assets/12224322/16408324/83d5213e-3d18-11e6-996c-551da89b57e7.JPG)
Its not a new issue but I just found multiple sliders instead of providing me a sentiment value of the tweets .

**Comment by johnsmithm** [comment]
There is already a task for multiple slider on the tweets page!

**Comment by alexbtk** [comment]
duplicate of #9. closed.
