### ISSUE TITLE
Unable to view company location 

### ISSUE THREAD

**Issue by rayss** [alexbtk/amos-ss16-proj9#12]
![unable to view location map](https://cloud.githubusercontent.com/assets/12224322/16408577/b976b928-3d19-11e6-81d6-9cfc88f65e48.JPG)
I have been trying it since yesterday ,but it gives me the same result , Is it because of slowing of DBpedia ?

**Comment by johnsmithm** [comment]
the task for location map is stil in the product backlog. I do not see some reason to open  a issue for it.

**Comment by alexbtk** [comment]
agree. closed.

**Comment by rayss** [comment]
It's agreed closed  , there was a confusion regarding this . As was discussed in a sprint .
