### ISSUE TITLE
Unable to view product sentiment graph

### ISSUE THREAD

**Issue by rayss** [alexbtk/amos-ss16-proj9#13]
![on clicking products](https://cloud.githubusercontent.com/assets/12224322/16408626/ec053b12-3d19-11e6-9d62-a11dc51e5219.JPG)

Its the same issue like the company location map , have been trying it since yesterday , could it be attributed to the limited quarters ?

**Comment by johnsmithm** [comment]
read the task for that graph, one must check some products first!!!
