### ISSUE TITLE
Products_duplication of "weeks slider" and go button

### ISSUE THREAD

**Issue by obaglai** [alexbtk/amos-ss16-proj9#14]
![image](https://cloud.githubusercontent.com/assets/18489355/16433644/a6c13818-3d8b-11e6-96f4-e628d305a7f0.png)

Steps:
1) entered site, inputted Apple Inc. 
2) Went to Products, put slider to 3 weeks, pressed go button.
3) did not work [response too long], loged out
4) logged in again
5) entered Apple Inc. again
6) went to Products, saw the screen attached

Is is a problem because I did not wait until the products appear? Or some cashing problem?
Anyway, some errors messages should be shown (like "please wait until the products load before pressing Go")

**Comment by obaglai** [comment]
okay, I found how it happened: if you press the "More info" on Product box, it appears again :). Can it be somehow disabled? thanks!
![image](https://cloud.githubusercontent.com/assets/18489355/16433921/02afd412-3d8d-11e6-8e5d-96cbedcfb986.png)

**Comment by johnsmithm** [comment]
fixed
