### ISSUE TITLE
Tone-Analysis function not working .

### ISSUE THREAD

**Issue by rayss** [alexbtk/amos-ss16-proj9#5]
Analysing Tone-Analysis API gives  ,Problem accessing /ss16/proj9/process. Reason: 
    Server Error and UnauthorizedException: Unauthorized: Access is denied due to invalid credentials .

{
    "credentials": {
        "url": "https://gateway.watsonplatform.net/tone-analyzer/api",
        "password": "RqhyoBcpdaBK",
        "username": "6a6df448-671c-475a-809e-278bedf45cc5"
    }
}

Had raised a ticket with IBM concerning the issue , who have confirmed the following .
---------- Forwarded message ----------
From: IBM - Customer Support support@bluemix.net
Date: Tue, May 24, 2016 at 10:56 PM
Subject: Ticket #5377-12605313 Awaiting Client Confirmation (| Sev 4 | credential not recognised)
To: "rayssrash@gmail.com" rayssrash@gmail.com

We're pleased to let you know that a resolution has been provided for your issue. It was our pleasure to work with you! Please click on the link to your ticket below to accept the resolution and you will be given an opportunity to provide feedback on
 our service. Our management teams review each response in an ongoing effort to maximize your experience with the IBM Support teams.

Rashmi,

 I successfully made a simple API call to Tone Analyzer via cURL using your provided credentials (see below). Thus your credentials are valid and are recognized. Issue lies somewhere else other than Tone Analyzer service. 

 You can test below cURL command your-self. 

$ curl -u 6a6df448-671c-475a-809e-278bedf45cc5:RqhyoBcpdaBK "https://gateway.watsonplatform.net/tone-analyzer/api/v3/tone?version=2016-05-19&text=A%20word%20is%20dead%20when%20it%20is%20said,%20some%20say.%20Emily%20Dickinson"

{"document_tone":{"tone_categories":[{"tones":[{"score":0.371059,"tone_id":"anger","tone_name":"Anger"},{"score":0.245303,"tone_id":"disgust","tone_name":"Disgust"},{"score":0.248368,"tone_id":"fear","tone_name":"Fear"},{"score":0.052157,"tone_id":"joy","tone_name":"Joy"},{"score":0.535403,"tone_id":"sadness","tone_name":"Sadness"}],"category_id":"emotion_tone","category_name":"Emotion Tone"},{"tones":[{"score":0.0,"tone_id":"analytical","tone_name":"Analytical"},{"score":0.0,"tone_id":"confident","tone_name":"Confident"},
 .
 .
 .
 ,{"score":0.489,"tone_id":"emotional_range_big5","tone_name":"Emotional Range"}],"category_id":"social_tone","category_name":"Social Tone"}]},{"sentence_id":1,"text":"Emily Dickinson","input_from":42,"input_to":57,"tone_categories":[]}]}

Thanks,

Atif
IBM Bluemix | Watson Services Support

The following email addresses have been CC'ed: rayssrash@gmail.com

Ticket Information: 
Ticket #: 5377-12605313 
Date Created: May 23, 2016 09:46 AM CDT 
Client Contact: Rashmi Routray (rayssrash@gmail.com) 
Current Status: Resolution Provided 
Summary: | Sev 4 | credential not recognised 
Details: Original Email Information

From: rayssrash@gmail.com

To: public-form@bluemix.net

Cc: 

---

A new ticket has been raised from the Support Widget.
 Details follow: IBM ID (or email) : rayssrash@gmail.com
Region : ibm:yp:eu-gb
Org : rayssrash@gmail.com (0b1741e3-7287-4716-8bc7-a7fee3792cef)
Space : dev (e88fac3e-d497-4dcb-a08b-2d035fa83f01)
App : Nicht zutreffend oder andere (Nicht zutreffend oder andere)
Service : Tone Analyzer-ds (6ed0e1d1-2b73-4e11-98a9-71bb4b37c82e)
Description : 
The credentials for my API are not getting recognised .

**Comment by DennisScheffer** [comment]
Same error for me. It seems that the tone analyzer is restricted to 1000 requests per month? Maybe that is the problem. We should be able to confirm that by next week since it will be June then.

**Comment by obaglai** [comment]
Tone analyser was excluded. Not relevant any more
