### ISSUE TITLE
Duplication of twitter slider

### ISSUE THREAD

**Issue by obaglai** [alexbtk/amos-ss16-proj9#9]
![twitter_slider_duplication](https://cloud.githubusercontent.com/assets/18489355/16396530/77f21a24-3cbf-11e6-819e-22f560446232.PNG)

**Comment by alexbtk** [comment]
fixed in https://github.com/alexbtk/amos-ss16-proj9/commit/65c0d8fd9609191f08aa6018d5b7948494b7e3f4
